# Generated by Django 3.0.5 on 2020-05-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabStorage', '0004_auto_20200501_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
