# Generated by Django 3.0.5 on 2020-05-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollabStorage', '0007_auto_20200502_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
