# Generated by Django 3.0.5 on 2020-05-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MLAlgorithm',
            new_name='RecAlgorithm',
        ),
        migrations.RenameModel(
            old_name='MLAlgorithmStatus',
            new_name='RecAlgorithmStatus',
        ),
        migrations.RenameModel(
            old_name='MLRequest',
            new_name='RecRequest',
        ),
    ]
