# Generated by Django 3.0.5 on 2020-05-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200530_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recalgorithmstatus',
            old_name='parent_mlalgorithm',
            new_name='parent_algorithm',
        ),
        migrations.RenameField(
            model_name='recrequest',
            old_name='parent_mlalgorithm',
            new_name='parent_algorithm',
        ),
    ]
