# Generated by Django 3.0.5 on 2020-04-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kstorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='parent_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
