# Generated by Django 3.0.5 on 2020-05-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kstorage', '0005_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
