# Generated by Django 3.0.5 on 2020-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kstorage', '0006_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='long_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_desc',
            field=models.TextField(null=True),
        ),
    ]
