# Generated by Django 3.0.5 on 2020-05-18 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kstorage', '0008_auto_20200502_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='project',
            name='long_desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='project',
            name='expertises',
        ),
        migrations.AddField(
            model_name='project',
            name='expertises',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='user',
            name='expertises',
        ),
        migrations.AddField(
            model_name='user',
            name='expertises',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
    ]
