# Generated by Django 3.0.5 on 2020-05-18 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kstorage', '0010_auto_20200518_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), default=list, size=None),
        ),
    ]
