# Generated by Django 3.0.5 on 2020-05-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kstorage', '0011_project_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='faculty',
            new_name='faculty_id',
        ),
    ]
