# Generated by Django 3.0.5 on 2020-06-01 09:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kstorage', '0014_auto_20200525_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='followed_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='starred_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='viewed_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
    ]
