# Generated by Django 3.0.5 on 2020-05-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectrelation',
            name='alg_type',
            field=models.CharField(default='UserProjectFieldsBased', max_length=50),
        ),
    ]
