# Generated by Django 3.0.5 on 2020-05-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_userprojectrelation_alg_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProjectRelation',
            new_name='Relation',
        ),
    ]
