# Generated by Django 3.0.5 on 2020-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_auto_20200526_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='alg_type',
            field=models.CharField(default='RelationCalcByFields', max_length=50),
        ),
    ]
